insert into career (pkid, name) values (1, 'Actor');
insert into career (pkid, name) values (2, 'Actuary');
insert into career (pkid, name) values (3, 'Advertising');
insert into career (pkid, name) values (4, 'Advocate');
insert into career (pkid, name) values (5, 'Aeronautical Engineer');
insert into career (pkid, name) values (6, 'Aeronautical information Clerk');
insert into career (pkid, name) values (7, 'Aeronautical Service Clerk');
insert into career (pkid, name) values (8, 'Agricultural Engineer');
insert into career (pkid, name) values (9, 'Agricultural Extension Officer');
insert into career (pkid, name) values (10, 'Agricultural Inspector');
insert into career (pkid, name) values (11, 'Agronomist');
insert into career (pkid, name) values (12, 'Air Traffic Controller');
insert into career (pkid, name) values (13, 'Ambulance & Emercency Care Giver');
insert into career (pkid, name) values (14, 'Animal Health and Protection');
insert into career (pkid, name) values (15, 'Animal Scientist');
insert into career (pkid, name) values (16, 'Aquatic Scientist');
insert into career (pkid, name) values (17, 'Archaeologist');
insert into career (pkid, name) values (18, 'Architect');
insert into career (pkid, name) values (19, 'Architectural Technologist');
insert into career (pkid, name) values (20, 'Archivist');
insert into career (pkid, name) values (21, 'Area Manager');
insert into career (pkid, name) values (22, 'Armament Fitter');
insert into career (pkid, name) values (23, 'Armature Winder');
insert into career (pkid, name) values (24, 'Art Editor and Critic');
insert into career (pkid, name) values (25, 'Artisen Training');
insert into career (pkid, name) values (26, 'Assayer and Sampler');
insert into career (pkid, name) values (27, 'Assemble Line Worker');
insert into career (pkid, name) values (28, 'Assistant Draughtsman');
insert into career (pkid, name) values (29, 'Astronomer');
insert into career (pkid, name) values (30, 'Atomic Energy Corporation');
insert into career (pkid, name) values (31, 'Attorney');
insert into career (pkid, name) values (32, 'Actioneer');
insert into career (pkid, name) values (33, 'Auditor');
insert into career (pkid, name) values (34, 'Automotive Body Repairer');
insert into career (pkid, name) values (35, 'Automotive Electrician');
insert into career (pkid, name) values (36, 'Automotive Machinist');
insert into career (pkid, name) values (37, 'Automotive Trimmer');
insert into career (pkid, name) values (38, 'Banking Career');
insert into career (pkid, name) values (39, 'Beer Brewer');
insert into career (pkid, name) values (40, 'Biochemist');
insert into career (pkid, name) values (41, 'Biokineticist');
insert into career (pkid, name) values (42, 'Biologist');
insert into career (pkid, name) values (43, 'Biomedical Engineer');
insert into career (pkid, name) values (44, 'Biomedical Technologist');
insert into career (pkid, name) values (45, 'Boiler Maker');
insert into career (pkid, name) values (46, 'Book Binder');
insert into career (pkid, name) values (47, 'Bookeeper');
insert into career (pkid, name) values (48, 'Botanist');
insert into career (pkid, name) values (49, 'Branch Manager');
insert into career (pkid, name) values (50, 'Bricklayer');
insert into career (pkid, name) values (51, 'Bus Driver');
insert into career (pkid, name) values (52, 'Business Economist');
insert into career (pkid, name) values (53, 'Cabin Attendent');
insert into career (pkid, name) values (54, 'Carpenter');
insert into career (pkid, name) values (55, 'Cartographer');
insert into career (pkid, name) values (56, 'Cashier');
insert into career (pkid, name) values (57, 'Ceramics Technologist');
insert into career (pkid, name) values (58, 'Chartered Accountant');
insert into career (pkid, name) values (59, 'Chartered Management Accountant');
insert into career (pkid, name) values (60, 'Chartered Secretary');
insert into career (pkid, name) values (61, 'Chemical Engineer');
insert into career (pkid, name) values (62, 'Chemist');
insert into career (pkid, name) values (63, 'Chiropractor');
insert into career (pkid, name) values (64, 'City Treasurer');
insert into career (pkid, name) values (65, 'Civil Engineer');
insert into career (pkid, name) values (66, 'Civil Investigator');
insert into career (pkid, name) values (67, 'Cleaner');
insert into career (pkid, name) values (68, 'Clergyman');
insert into career (pkid, name) values (69, 'Clerk');
insert into career (pkid, name) values (70, 'Clinical Engineering Technician');
insert into career (pkid, name) values (71, 'Clinical Technologist');
insert into career (pkid, name) values (72, 'Clothing Designer');
insert into career (pkid, name) values (73, 'Clothing Manager');
insert into career (pkid, name) values (74, 'Coal Technologist');
insert into career (pkid, name) values (75, 'Cobbler');
insert into career (pkid, name) values (76, 'Committee Clerk');
insert into career (pkid, name) values (77, 'Computer Technician');
insert into career (pkid, name) values (78, 'Concrete Technologist');
insert into career (pkid, name) values (79, 'Conservation and Wildlife Manager');
insert into career (pkid, name) values (80, 'Construction Manager');
insert into career (pkid, name) values (81, 'Copy-writer');
insert into career (pkid, name) values (82, 'Correctional Services');
insert into career (pkid, name) values (83, 'Costume Designer');
insert into career (pkid, name) values (84, 'Crane Operator');
insert into career (pkid, name) values (85, 'Credit Controller');
insert into career (pkid, name) values (86, 'Crop Protection Services');
insert into career (pkid, name) values (87, 'Customer Service Agent');
insert into career (pkid, name) values (88, 'Customs and Excise Officer');
insert into career (pkid, name) values (89, 'Dancer');
insert into career (pkid, name) values (90, 'Dealer ');
insert into career (pkid, name) values (91, 'Décor Designer');
insert into career (pkid, name) values (92, 'Dental Assistant and Oral Health');
insert into career (pkid, name) values (93, 'Dental Technician');
insert into career (pkid, name) values (94, 'Dental Therapist');
insert into career (pkid, name) values (95, 'Dentist');
insert into career (pkid, name) values (96, 'Diamond Cutter');
insert into career (pkid, name) values (97, 'Diesel Fitter');
insert into career (pkid, name) values (98, 'Diesel Loco Driver');
insert into career (pkid, name) values (99, 'Diesel Mechanic');
insert into career (pkid, name) values (100, 'Die-Sinker and Engraver');
insert into career (pkid, name) values (101, 'Dietician');
insert into career (pkid, name) values (102, 'Driver');
insert into career (pkid, name) values (103, 'Domestic Appliance Technician');
insert into career (pkid, name) values (104, 'Domestic Personnel');
insert into career (pkid, name) values (105, 'Domestic Radio and TV Technician');
insert into career (pkid, name) values (106, 'Domestic Worker');
insert into career (pkid, name) values (107, 'Draughtsman');
insert into career (pkid, name) values (108, 'Drivers Assistant');
insert into career (pkid, name) values (109, 'Earth Moving Mechanic');
insert into career (pkid, name) values (110, 'Ecologist');
insert into career (pkid, name) values (111, 'Economist');
insert into career (pkid, name) values (112, 'Electronic Engineer');
insert into career (pkid, name) values (113, 'Electrical Engineer');
insert into career (pkid, name) values (114, 'Electrician');
insert into career (pkid, name) values (115, 'Engineer');
insert into career (pkid, name) values (116, 'Engineering Technician');
insert into career (pkid, name) values (117, 'Entomologist');
insert into career (pkid, name) values (118, 'Environmental Health Officer');
insert into career (pkid, name) values (119, 'Estate Agent');
insert into career (pkid, name) values (120, 'Explosive Expert');
insert into career (pkid, name) values (121, 'Explosive Technologist');
insert into career (pkid, name) values (122, 'Extractive Metallurgist');
insert into career (pkid, name) values (123, 'Farmer');
insert into career (pkid, name) values (124, 'Farm Manager');
insert into career (pkid, name) values (125, 'Farm Worker');
insert into career (pkid, name) values (126, 'Farrier');
insert into career (pkid, name) values (127, 'Fashion Buyer');
insert into career (pkid, name) values (128, 'Fibreglass Technician');
insert into career (pkid, name) values (129, 'Film Producer');
insert into career (pkid, name) values (130, 'Financial & Investment Manager');
insert into career (pkid, name) values (131, 'Fire Fighter');
insert into career (pkid, name) values (132, 'Fitter and Turner');
insert into career (pkid, name) values (133, 'Flight Engineer');
insert into career (pkid, name) values (134, 'Florist');
insert into career (pkid, name) values (135, 'Food Technologist');
insert into career (pkid, name) values (136, 'Footwear Technologist');
insert into career (pkid, name) values (137, 'Foreign Services');
insert into career (pkid, name) values (138, 'Forester');
insert into career (pkid, name) values (139, 'Fruit & Veg Technologist');
insert into career (pkid, name) values (140, 'Funeral Director');
insert into career (pkid, name) values (141, 'Furrier');
insert into career (pkid, name) values (142, 'Game Ranger');
insert into career (pkid, name) values (143, 'Gardener');
insert into career (pkid, name) values (144, 'Geneticist');
insert into career (pkid, name) values (145, 'Geographer');
insert into career (pkid, name) values (146, 'Geologist');
insert into career (pkid, name) values (147, 'Goldsmith');
insert into career (pkid, name) values (148, 'Geotechnologist');
insert into career (pkid, name) values (149, 'Grain Grader');
insert into career (pkid, name) values (150, 'Graphic Designer');
insert into career (pkid, name) values (151, 'Grassland Scientist');
insert into career (pkid, name) values (152, 'Green Keeper');
insert into career (pkid, name) values (153, 'Gravure Machine Minder');
insert into career (pkid, name) values (154, 'Hairdresser');
insert into career (pkid, name) values (155, 'Herpetologist');
insert into career (pkid, name) values (156, 'Home Economist');
insert into career (pkid, name) values (157, 'Homeopath');
insert into career (pkid, name) values (158, 'Horticulturist');
insert into career (pkid, name) values (159, 'Hospitality Industry');
insert into career (pkid, name) values (160, 'Hospital Porter');
insert into career (pkid, name) values (161, 'Human Resource Officer');
insert into career (pkid, name) values (162, 'Human Resource Manager');
insert into career (pkid, name) values (163, 'Hydrologist  (surface water)');
insert into career (pkid, name) values (164, 'Industrial Designer');
insert into career (pkid, name) values (165, 'Industrial Engineer');
insert into career (pkid, name) values (166, 'Industrial Technologist');
insert into career (pkid, name) values (167, 'Inspector');
insert into career (pkid, name) values (168, 'Instrument Maker');
insert into career (pkid, name) values (169, 'Instrument Mechanic');
insert into career (pkid, name) values (170, 'Insurance Industry');
insert into career (pkid, name) values (171, 'Interior Designer');
insert into career (pkid, name) values (172, 'Inventory Manager');
insert into career (pkid, name) values (173, 'Jockey');
insert into career (pkid, name) values (174, 'Joiner');
insert into career (pkid, name) values (175, 'Journalist');
insert into career (pkid, name) values (176, 'Knitter');
insert into career (pkid, name) values (177, 'Labourer');
insert into career (pkid, name) values (178, 'Landscape Architect');
insert into career (pkid, name) values (179, 'Land Surveyor');
insert into career (pkid, name) values (180, 'Lawyer');
insert into career (pkid, name) values (181, 'Leather Technologist ');
insert into career (pkid, name) values (182, 'Leather Chemist');
insert into career (pkid, name) values (183, 'Lecturer');
insert into career (pkid, name) values (184, 'Legal Assistant');
insert into career (pkid, name) values (185, 'Librarian');
insert into career (pkid, name) values (186, 'Life Guard');
insert into career (pkid, name) values (187, 'Lift Mechanic');
insert into career (pkid, name) values (188, 'Linesman');
insert into career (pkid, name) values (189, 'Lithographic Machine Minder');
insert into career (pkid, name) values (190, 'Locksmith');
insert into career (pkid, name) values (191, 'Machine Operator');
insert into career (pkid, name) values (192, 'Magistrate');
insert into career (pkid, name) values (193, 'Mail Delivery Handler');
insert into career (pkid, name) values (194, 'Makeup Artist');
insert into career (pkid, name) values (195, 'Management Consultant');
insert into career (pkid, name) values (196, 'Manager');
insert into career (pkid, name) values (197, 'Marine Biologist');
insert into career (pkid, name) values (198, 'Marketing ');
insert into career (pkid, name) values (199, 'Material Engineer');
insert into career (pkid, name) values (200, 'Mathematician');
insert into career (pkid, name) values (201, 'Matron ');
insert into career (pkid, name) values (202, 'Measurement Technician');
insert into career (pkid, name) values (203, 'Meat Cutting Technician');
insert into career (pkid, name) values (204, 'Meat Inspector');
insert into career (pkid, name) values (205, 'Mechanical Engineer');
insert into career (pkid, name) values (206, 'Medical Doctor');
insert into career (pkid, name) values (207, 'Medical Prosthesis Technician');
insert into career (pkid, name) values (208, 'Medical Physicist');
insert into career (pkid, name) values (209, 'Medical Representative');
insert into career (pkid, name) values (210, 'Merchandise Planner');
insert into career (pkid, name) values (211, 'Messenger');
insert into career (pkid, name) values (212, 'Metalurgist');
insert into career (pkid, name) values (213, 'Meteorologist Technician');
insert into career (pkid, name) values (214, 'Meter Reader');
insert into career (pkid, name) values (215, 'Microbiologist');
insert into career (pkid, name) values (216, 'Miller');
insert into career (pkid, name) values (217, 'Millwright');
insert into career (pkid, name) values (218, 'Miner');
insert into career (pkid, name) values (219, 'Mine Surveyor');
insert into career (pkid, name) values (220, 'Mining Assistant');
insert into career (pkid, name) values (221, 'Mining Engineer');
insert into career (pkid, name) values (222, 'Model');
insert into career (pkid, name) values (223, 'Model Builder');
insert into career (pkid, name) values (224, 'Motor Cycle Mechanic');
insert into career (pkid, name) values (225, 'Motor Mechanic');
insert into career (pkid, name) values (226, 'Moulder');
insert into career (pkid, name) values (227, 'Museum Caretakers');
insert into career (pkid, name) values (228, 'Musicians');
insert into career (pkid, name) values (229, 'Nature Conservation');
insert into career (pkid, name) values (230, 'Navigator');
insert into career (pkid, name) values (231, 'Nuclear Scientist');
insert into career (pkid, name) values (232, 'Nursing ');
insert into career (pkid, name) values (233, 'Occupational Therapist');
insert into career (pkid, name) values (234, 'Oceanographer');
insert into career (pkid, name) values (235, 'Operations Researcher');
insert into career (pkid, name) values (236, 'Optical Dispenser');
insert into career (pkid, name) values (237, 'Optical Technician');
insert into career (pkid, name) values (238, 'Optometrist');
insert into career (pkid, name) values (239, 'Ornithologist');
insert into career (pkid, name) values (240, 'Painter & Decorator');
insert into career (pkid, name) values (241, 'Paint Technician');
insert into career (pkid, name) values (242, 'Paper Technologist');
insert into career (pkid, name) values (243, 'Patent Attorney');
insert into career (pkid, name) values (244, 'Pattern Maker (Clothing)');
insert into career (pkid, name) values (245, 'Patternmaker (Engineering)');
insert into career (pkid, name) values (246, 'Personnel Consultant');
insert into career (pkid, name) values (247, 'Petroleum Technologist');
insert into career (pkid, name) values (248, 'Petrol Attendent');
insert into career (pkid, name) values (249, 'Pharmacist');
insert into career (pkid, name) values (250, 'Pharmacist Assistant');
insert into career (pkid, name) values (251, 'Photo Lithographer');
insert into career (pkid, name) values (252, 'Photographer');
insert into career (pkid, name) values (253, 'Physicist');
insert into career (pkid, name) values (254, 'Physiologist');
insert into career (pkid, name) values (255, 'Physiotherapist');
insert into career (pkid, name) values (256, 'Piano Tuner');
insert into career (pkid, name) values (257, 'Pilot');
insert into career (pkid, name) values (258, 'Plasterer and Tiler');
insert into career (pkid, name) values (259, 'Plastic Technologist');
insert into career (pkid, name) values (260, 'Plumber');
insert into career (pkid, name) values (261, 'Podiatrist');
insert into career (pkid, name) values (262, 'Post Office Clerk');
insert into career (pkid, name) values (263, 'Power Plant Operator');
insert into career (pkid, name) values (264, 'Printer Mechanic');
insert into career (pkid, name) values (265, 'Private Secretary');
insert into career (pkid, name) values (266, 'Process Operator');
insert into career (pkid, name) values (267, 'Production Manager');
insert into career (pkid, name) values (268, 'Production Operator');
insert into career (pkid, name) values (269, 'Projectionist');
insert into career (pkid, name) values (270, 'Psychologist');
insert into career (pkid, name) values (271, 'Psychometrist');
insert into career (pkid, name) values (272, 'Psychiatrist');
insert into career (pkid, name) values (273, 'Public Administrator');
insert into career (pkid, name) values (274, 'Public Prosecutor');
insert into career (pkid, name) values (275, 'Public Relations Officer');
insert into career (pkid, name) values (276, 'Pulp and Paper Technologist');
insert into career (pkid, name) values (277, 'Purchasing Manager');
insert into career (pkid, name) values (278, 'Quality Controller');
insert into career (pkid, name) values (279, 'Quantity Surveyor');
insert into career (pkid, name) values (280, 'Radiation Protectorist');
insert into career (pkid, name) values (281, 'Radio Technician');
insert into career (pkid, name) values (282, 'Radiographer');
insert into career (pkid, name) values (283, 'Receptionist');
insert into career (pkid, name) values (284, 'Recreation Manager');
insert into career (pkid, name) values (285, 'Refrigeration Mechanic');
insert into career (pkid, name) values (286, 'Rigger');
insert into career (pkid, name) values (287, 'Road Construction Plant Operator');
insert into career (pkid, name) values (288, 'Roofer');
insert into career (pkid, name) values (289, 'Rubber Technologist');
insert into career (pkid, name) values (290, 'Sales Person');
insert into career (pkid, name) values (291, 'Sales Representative');
insert into career (pkid, name) values (292, 'Saw Technician');
insert into career (pkid, name) values (293, 'Scale Technician');
insert into career (pkid, name) values (294, 'School Councillor');
insert into career (pkid, name) values (295, 'Security Officer');
insert into career (pkid, name) values (296, 'Sewing Machine Technician');
insert into career (pkid, name) values (297, 'Sheet Metal worker');
insert into career (pkid, name) values (298, 'Shop Assistant');
insert into career (pkid, name) values (299, 'Shop Fitter');
insert into career (pkid, name) values (300, 'Singer');
insert into career (pkid, name) values (301, 'Social Worker');
insert into career (pkid, name) values (302, 'Sociologist');
insert into career (pkid, name) values (303, 'Soil Technician');
insert into career (pkid, name) values (304, 'Somatologist');
insert into career (pkid, name) values (305, 'Speech Therapist');
insert into career (pkid, name) values (306, 'Sports Manager');
insert into career (pkid, name) values (307, 'Sports Trainer');
insert into career (pkid, name) values (308, 'Spray Painter');
insert into career (pkid, name) values (309, 'Statistician');
insert into career (pkid, name) values (310, 'Stock Broker');
insert into career (pkid, name) values (311, 'Swimming Pool Technician');
insert into career (pkid, name) values (312, 'Tailor');
insert into career (pkid, name) values (313, 'Taxidermist');
insert into career (pkid, name) values (314, 'Tax Consultant');
insert into career (pkid, name) values (315, 'Teacher');
insert into career (pkid, name) values (316, 'Technical Illustrator');
insert into career (pkid, name) values (317, 'Technical Writer');
insert into career (pkid, name) values (318, 'Teller');
insert into career (pkid, name) values (319, 'Terminologist');
insert into career (pkid, name) values (320, 'Textile Designer');
insert into career (pkid, name) values (321, 'Theatre Technologist');
insert into career (pkid, name) values (322, 'Tool and Die Maker');
insert into career (pkid, name) values (323, 'Tour Manager');
insert into career (pkid, name) values (324, 'Tourist Guide');
insert into career (pkid, name) values (325, 'Town Planner');
insert into career (pkid, name) values (326, 'Tractor and Agriculture Technician');
insert into career (pkid, name) values (327, 'Trade Testing Officer');
insert into career (pkid, name) values (328, 'Traffic Officer');
insert into career (pkid, name) values (329, 'Translator');
insert into career (pkid, name) values (330, 'Travel Agent');
insert into career (pkid, name) values (331, 'Truck Driver');
insert into career (pkid, name) values (332, 'Typist');
insert into career (pkid, name) values (333, 'Valuator and Appraisor');
insert into career (pkid, name) values (334, 'Veterinary Surgeon');
insert into career (pkid, name) values (335, 'Veterinary Technolgist');
insert into career (pkid, name) values (336, 'Viticulturist');
insert into career (pkid, name) values (337, 'Watchmaker');
insert into career (pkid, name) values (338, 'Water Supply Technologist');
insert into career (pkid, name) values (339, 'Weather Observer');
insert into career (pkid, name) values (340, 'Weaver');
insert into career (pkid, name) values (341, 'Welder');
insert into career (pkid, name) values (342, 'Wine Maker');
insert into career (pkid, name) values (343, 'Wood Scientist');
insert into career (pkid, name) values (344, 'Wood Technologist');
insert into career (pkid, name) values (345, 'Wood Worker');
insert into career (pkid, name) values (346, 'Wool Classifier');
insert into career (pkid, name) values (347, 'Wrapper and Labeler');
insert into career (pkid, name) values (348, 'Yard Official');
insert into career (pkid, name) values (349, 'Zoologist');