TRUNCATE construct;

INSERT INTO construct VALUES (1, 1, 'Achievement IIS', NULL, false, true, false);
INSERT INTO construct VALUES (2, 1, 'Achievement GBS', NULL, false, true, false);
INSERT INTO construct VALUES (3, 1, 'Satisfaction IIS', NULL, false, true, false);
INSERT INTO construct VALUES (4, 1, 'Satisfaction GBS', NULL, false, true, false);
INSERT INTO construct VALUES (5, 1, 'Expectation IIS', NULL, false, true, false);
INSERT INTO construct VALUES (6, 1, 'Expectation GBS', NULL, false, true, false);
INSERT INTO construct VALUES (7, 2, 'Frustration IIS', NULL, false, false, false);
INSERT INTO construct VALUES (8, 2, 'Frustration GBS', NULL, false, false, false);
INSERT INTO construct VALUES (9, 2, 'Stress IIS', NULL, false, false, false);
INSERT INTO construct VALUES (10, 2, 'Stress GBS', NULL, false, false, false);
INSERT INTO construct VALUES (11, 2, 'Helplessness IIS', NULL, false, false, false);
INSERT INTO construct VALUES (12, 2, 'Helplessness GBS', NULL, false, false, false);
INSERT INTO construct VALUES (13, 3, 'Inner Insecurity', NULL, false, false, false);
INSERT INTO construct VALUES (14, 3, 'Guilt Feelings', NULL, false, false, false);
INSERT INTO construct VALUES (15, 3, 'Lack of Self worth', NULL, false, false, false);
INSERT INTO construct VALUES (16, 3, 'Stigma', NULL, false, false, false);
INSERT INTO construct VALUES (17, 3, 'Body Image', NULL, false, false, false);
INSERT INTO construct VALUES (18, 4, 'Relationship with Colleagues', NULL, false, true, false);
INSERT INTO construct VALUES (19, 4, 'Relationship with Partner', NULL, false, true, false);
INSERT INTO construct VALUES (20, 4, 'Relationships with Son', NULL, false, true, false);
INSERT INTO construct VALUES (21, 4, 'Relationships with Daughter', NULL, false, true, false);
INSERT INTO construct VALUES (22, 4, 'Relationships: General', NULL, false, true, false);
INSERT INTO construct VALUES (23, 4, 'Relationships: Stepson', NULL, false, true, false);
INSERT INTO construct VALUES (24, 4, 'Relationships: Stepdaughter', NULL, false, true, false);
INSERT INTO construct VALUES (25, 4, 'Relationships: Stepmother', NULL, false, true, false);
INSERT INTO construct VALUES (26, 4, 'Relationships: Stepfather', NULL, false, true, false);
INSERT INTO construct VALUES (27, 5, 'Financial Planning', NULL, false, true, false);
INSERT INTO construct VALUES (28, 5, 'Financial Control', NULL, false, true, false);
INSERT INTO construct VALUES (29, 5, 'Financial Discipline', NULL, false, true, false);
INSERT INTO construct VALUES (30, 6, 'Job Satisfaction', NULL, false, true, false);
INSERT INTO construct VALUES (31, 6, 'Job Security', NULL, false, true, false);
INSERT INTO construct VALUES (32, 6, 'Equality', NULL, false, true, false);
INSERT INTO construct VALUES (33, 6, 'Effectiveness of Supervisor', NULL, false, true, false);
INSERT INTO construct VALUES (34, 6, 'Supervisors Leadership Ability', NULL, false, true, false);
INSERT INTO construct VALUES (35, 6, 'Supervisors Communication Skills', NULL, false, true, false);
INSERT INTO construct VALUES (36, 6, 'Supervisors Listening Skills', NULL, false, true, false);
INSERT INTO construct VALUES (37, 6, 'Supervisors Competence', NULL, false, true, false);
INSERT INTO construct VALUES (38, 6, 'Supervisors Positive Attitude', NULL, false, true, false);
INSERT INTO construct VALUES (39, 6, 'Supervisors Problem Solving Ability', NULL, false, true, false);
INSERT INTO construct VALUES (40, 6, 'Supervisors Ability to Serve', NULL, false, true, false);
INSERT INTO construct VALUES (41, 6, 'Supervisors Reliability', NULL, false, true, false);
INSERT INTO construct VALUES (42, 7, 'Dependency', NULL, false, false, false);
INSERT INTO construct VALUES (43, 7, 'Disturbing Thoughts', NULL, false, false, false);
INSERT INTO construct VALUES (44, 7, 'Memory Loss', NULL, false, false, false);
INSERT INTO construct VALUES (45, 7, 'Paranoia', NULL, false, false, false);
INSERT INTO construct VALUES (46, 7, 'Anxiety', NULL, false, false, false);
INSERT INTO construct VALUES (47, 7, 'Suicidal Thoughts', NULL, false, false, false);
INSERT INTO construct VALUES (48, 7, 'Senselessness of Existence', NULL, false, false, false);
INSERT INTO construct VALUES (49, 8, 'Ability Utilization', NULL, false, false, true);
INSERT INTO construct VALUES (50, 8, 'Interest in People', NULL, false, false, true);
INSERT INTO construct VALUES (51, 8, 'Autonomy', NULL, false, false, true);
INSERT INTO construct VALUES (52, 8, 'Authority', NULL, false, false, true);
INSERT INTO construct VALUES (53, 8, 'Originality', NULL, false, false, true);
INSERT INTO construct VALUES (54, 8, 'Financial Compensation', NULL, false, false, true);
INSERT INTO construct VALUES (55, 8, 'Freedom Of Lifestyle', NULL, false, false, true);
INSERT INTO construct VALUES (56, 8, 'Status', NULL, false, false, true);
INSERT INTO construct VALUES (57, 8, 'Risk', NULL, false, false, true);
INSERT INTO construct VALUES (58, 8, 'Financial Guarantee', NULL, false, false, true);
INSERT INTO construct VALUES (59, 8, 'Personal Standards', NULL, false, false, true);
INSERT INTO construct VALUES (60, 8, 'Cultural Prejudice', NULL, false, false, true);
INSERT INTO construct VALUES (61, 8, 'Artistic Appreciation', NULL, false, false, true);
INSERT INTO construct VALUES (62, 8, 'Social Interaction', NULL, false, false, true);
INSERT INTO construct VALUES (63, 8, 'Physical Activities', NULL, false, false, true);
INSERT INTO construct VALUES (64, 8, 'Predictable Environment', NULL, false, false, true);
INSERT INTO construct VALUES (65, 8, 'Personal Development', NULL, false, false, true);
INSERT INTO construct VALUES (66, 8, 'Challenging Attributes', NULL, false, false, true);
INSERT INTO construct VALUES (67, 8, 'Multi Tasking', NULL, false, false, true);
INSERT INTO construct VALUES (68, 8, 'Servanthood', NULL, false, false, true);
INSERT INTO construct VALUES (69, 8, 'Result Orientation', NULL, false, false, true);
INSERT INTO construct VALUES (70, 8, 'Physical Challenges', NULL, false, false, true);
INSERT INTO construct VALUES (71, 9, 'Leadership Ability', NULL, false, false, true);
INSERT INTO construct VALUES (80, 9, 'Problem Solving Ability', NULL, false, false, true);
INSERT INTO construct VALUES (72, 10, 'Competence', NULL, false, false, true);
INSERT INTO construct VALUES (76, 10, 'Initiative', NULL, false, false, true);
INSERT INTO construct VALUES (81, 10, 'Responsibility', NULL, false, false, true);
INSERT INTO construct VALUES (83, 10, 'Reliability', NULL, false, false, true);
INSERT INTO construct VALUES (84, 10, 'Patience', NULL, false, false, true);
INSERT INTO construct VALUES (85, 10, 'Perseverance', NULL, false, false, true);
INSERT INTO construct VALUES (73, 11, 'Commitment', NULL, false, false, true);
INSERT INTO construct VALUES (75, 11, 'Focus', NULL, false, false, true);
INSERT INTO construct VALUES (78, 11, 'Passion', NULL, false, false, true);
INSERT INTO construct VALUES (79, 11, 'Positive Attitude', NULL, false, false, true);
INSERT INTO construct VALUES (82, 11, 'Self - Discipline', NULL, false, false, true);
INSERT INTO construct VALUES (74, 12, 'Communication Skills', NULL, false, false, true);
INSERT INTO construct VALUES (77, 12, 'Listening Skills', NULL, false, false, true);
INSERT INTO construct VALUES (86, 12, 'Interpersonal', NULL, false, false, true);
INSERT INTO construct VALUES (87, 13, 'Perseverance', NULL, false, false, false);
INSERT INTO construct VALUES (88, 13, 'Satisfaction', NULL, false, false, false);
INSERT INTO construct VALUES (89, 13, 'Future Perspectives', NULL, false, false, false);
INSERT INTO construct VALUES (90, 13, 'Anxiety', NULL, false, false, false);
INSERT INTO construct VALUES (91, 13, 'Guilt Feelings', NULL, false, false, false);
INSERT INTO construct VALUES (92, 13, 'Lack of Self Worth', NULL, false, false, false);
INSERT INTO construct VALUES (93, 13, 'Isolation', NULL, false, false, false);
INSERT INTO construct VALUES (94, 13, 'Responsible for Others', NULL, false, false, false);
INSERT INTO construct VALUES (95, 13, 'Lack of Assertiveness', NULL, false, false, false);
INSERT INTO construct VALUES (96, 13, 'Memory Loss', NULL, false, false, false);
INSERT INTO construct VALUES (97, 13, 'Frustration', NULL, false, false, false);
INSERT INTO construct VALUES (98, 13, 'Helplessness', NULL, false, false, false);
INSERT INTO construct VALUES (99, 13, 'Attitude towards Adults', NULL, false, false, false);
INSERT INTO construct VALUES (100, 13, 'Mistrust', NULL, false, false, false);
INSERT INTO construct VALUES (101, 13, 'Inferiority Complex', NULL, false, false, false);
INSERT INTO construct VALUES (102, 13, 'Body Image', NULL, false, false, false);
INSERT INTO construct VALUES (103, 13, 'Personal Boundaries', NULL, false, false, false);
INSERT INTO construct VALUES (104, 13, 'School Problems', NULL, false, false, false);
INSERT INTO construct VALUES (105, 14, 'Family (Where You Stay)', NULL, false, true, false);
INSERT INTO construct VALUES (106, 14, 'Relationship with Friends', NULL, false, true, false);
INSERT INTO construct VALUES (107, 14, 'Relationship with Mother', NULL, false, true, false);
INSERT INTO construct VALUES (108, 14, 'Relationship with Father', NULL, false, true, false);
INSERT INTO construct VALUES (109, 14, 'Relationship with Stepmother', NULL, false, true, false);
INSERT INTO construct VALUES (110, 14, 'Relationship with Stepfather', NULL, false, true, false);
INSERT INTO construct VALUES (111, 14, 'Relationships at School', NULL, false, true, false);
INSERT INTO construct VALUES (112, 14, 'Relationship with Teachers', NULL, false, true, false);
INSERT INTO construct VALUES (113, 14, 'Relationship with Brother', NULL, false, true, false);
INSERT INTO construct VALUES (114, 14, 'Relationship with Sister', NULL, false, true, false);
INSERT INTO construct VALUES (115, 15, 'Service', NULL, false, false, false);
INSERT INTO construct VALUES (116, 15, 'General Culture', NULL, false, false, false);
INSERT INTO construct VALUES (117, 15, 'Entrepreneur', NULL, false, false, false);
INSERT INTO construct VALUES (118, 15, 'Business Interaction', NULL, false, false, false);
INSERT INTO construct VALUES (119, 15, 'Technology', NULL, false, false, false);
INSERT INTO construct VALUES (120, 15, 'Science', NULL, false, false, false);
INSERT INTO construct VALUES (121, 15, 'Outdoors', NULL, false, false, false);
INSERT INTO construct VALUES (122, 15, 'Arts', NULL, false, false, false);
INSERT INTO construct VALUES (123, 15, 'Entertainment', NULL, false, false, false);
INSERT INTO construct VALUES (124, 15, 'Mechanical', NULL, false, false, false);
INSERT INTO construct VALUES (125, 15, 'Medical', NULL, false, false, false);
INSERT INTO construct VALUES (126, 15, 'Training', NULL, false, false, false);
INSERT INTO construct VALUES (127, 15, 'Administration', NULL, false, false, false);
INSERT INTO construct VALUES (128, 15, 'Human Resources', NULL, false, false, false);
INSERT INTO construct VALUES (129, 15, 'Aeronautics', NULL, false, false, false);
INSERT INTO construct VALUES (130, 15, 'Marketing', NULL, false, true, false);
INSERT INTO construct VALUES (131, 15, 'Research', NULL, false, false, false);
INSERT INTO construct VALUES (132, 15, 'Communications', NULL, false, false, false);

-- mark all optional
UPDATE construct SET isoptional = true;